# -*- coding: utf-8 -*-
from LIBRARY import *


LOG_THIS('NOTICE','================================================================================================================================================================')


#import AKOAM,AKOAMCAM,AKWAM,ALARAB,ALFATIMI,ALKAWTHAR,ALMAAREF,ARABSEED,BOKRA,CIMANOW,DAILYMOTION,DOWNLOAD,EGYBEST,FAJERSHOW,FAVOURITES,IFILM,IPTV,KARBALATV,LIVETV,MENUS,MOVS4U,MYCIMA,PANET,RANDOMS,SERVICES,SHAHID4U,SHIAVOICE,SHOOFMAX,YOUTUBE,YTB_CHANNELS,RESOLVERS,FASELHD,LIBRARY
#import HALACIMA,ARBLIONZ,EGYBESTVIP,HELAL,MOVIZLAND,SERIES4WATCH


#a = READ_FROM_SQL3('MISC','USERAGENT123')
#DIALOG_OK(str(a),str(a))


DIALOG_BUSY('start')


try: MAIN()
except Exception as error: HANDLE_EXIT_ERRORS(error)


DIALOG_BUSY('stop')




